services:
  web:
    image: ikkyuz/react-demo1
    container_name: react-demo
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - caddy

networks:
  caddy:
    external: true